/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UbaRouteImport } from './routes/uba'
import { Route as ThreatIntelRouteImport } from './routes/threat-intel'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as MitreRouteImport } from './routes/mitre'
import { Route as LiveLogsRouteImport } from './routes/live-logs'
import { Route as IocRouteImport } from './routes/ioc'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FimRouteImport } from './routes/fim'
import { Route as EndpointRouteImport } from './routes/endpoint'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as AuthenticationRouteImport } from './routes/authentication'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AiAnalysisRouteImport } from './routes/ai-analysis'
import { Route as IndexRouteImport } from './routes/index'

const UbaRoute = UbaRouteImport.update({
  id: '/uba',
  path: '/uba',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreatIntelRoute = ThreatIntelRouteImport.update({
  id: '/threat-intel',
  path: '/threat-intel',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const MitreRoute = MitreRouteImport.update({
  id: '/mitre',
  path: '/mitre',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveLogsRoute = LiveLogsRouteImport.update({
  id: '/live-logs',
  path: '/live-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const IocRoute = IocRouteImport.update({
  id: '/ioc',
  path: '/ioc',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FimRoute = FimRouteImport.update({
  id: '/fim',
  path: '/fim',
  getParentRoute: () => rootRouteImport,
} as any)
const EndpointRoute = EndpointRouteImport.update({
  id: '/endpoint',
  path: '/endpoint',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticationRoute = AuthenticationRouteImport.update({
  id: '/authentication',
  path: '/authentication',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAnalysisRoute = AiAnalysisRouteImport.update({
  id: '/ai-analysis',
  path: '/ai-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-analysis': typeof AiAnalysisRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/authentication': typeof AuthenticationRoute
  '/cases': typeof CasesRoute
  '/endpoint': typeof EndpointRoute
  '/fim': typeof FimRoute
  '/help': typeof HelpRoute
  '/incidents': typeof IncidentsRoute
  '/integrations': typeof IntegrationsRoute
  '/ioc': typeof IocRoute
  '/live-logs': typeof LiveLogsRoute
  '/mitre': typeof MitreRoute
  '/network': typeof NetworkRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/rules': typeof RulesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/threat-intel': typeof ThreatIntelRoute
  '/uba': typeof UbaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-analysis': typeof AiAnalysisRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/authentication': typeof AuthenticationRoute
  '/cases': typeof CasesRoute
  '/endpoint': typeof EndpointRoute
  '/fim': typeof FimRoute
  '/help': typeof HelpRoute
  '/incidents': typeof IncidentsRoute
  '/integrations': typeof IntegrationsRoute
  '/ioc': typeof IocRoute
  '/live-logs': typeof LiveLogsRoute
  '/mitre': typeof MitreRoute
  '/network': typeof NetworkRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/rules': typeof RulesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/threat-intel': typeof ThreatIntelRoute
  '/uba': typeof UbaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-analysis': typeof AiAnalysisRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/authentication': typeof AuthenticationRoute
  '/cases': typeof CasesRoute
  '/endpoint': typeof EndpointRoute
  '/fim': typeof FimRoute
  '/help': typeof HelpRoute
  '/incidents': typeof IncidentsRoute
  '/integrations': typeof IntegrationsRoute
  '/ioc': typeof IocRoute
  '/live-logs': typeof LiveLogsRoute
  '/mitre': typeof MitreRoute
  '/network': typeof NetworkRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/rules': typeof RulesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/threat-intel': typeof ThreatIntelRoute
  '/uba': typeof UbaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-analysis'
    | '/alerts'
    | '/analytics'
    | '/authentication'
    | '/cases'
    | '/endpoint'
    | '/fim'
    | '/help'
    | '/incidents'
    | '/integrations'
    | '/ioc'
    | '/live-logs'
    | '/mitre'
    | '/network'
    | '/profile'
    | '/reports'
    | '/rules'
    | '/search'
    | '/settings'
    | '/threat-intel'
    | '/uba'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-analysis'
    | '/alerts'
    | '/analytics'
    | '/authentication'
    | '/cases'
    | '/endpoint'
    | '/fim'
    | '/help'
    | '/incidents'
    | '/integrations'
    | '/ioc'
    | '/live-logs'
    | '/mitre'
    | '/network'
    | '/profile'
    | '/reports'
    | '/rules'
    | '/search'
    | '/settings'
    | '/threat-intel'
    | '/uba'
  id:
    | '__root__'
    | '/'
    | '/ai-analysis'
    | '/alerts'
    | '/analytics'
    | '/authentication'
    | '/cases'
    | '/endpoint'
    | '/fim'
    | '/help'
    | '/incidents'
    | '/integrations'
    | '/ioc'
    | '/live-logs'
    | '/mitre'
    | '/network'
    | '/profile'
    | '/reports'
    | '/rules'
    | '/search'
    | '/settings'
    | '/threat-intel'
    | '/uba'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAnalysisRoute: typeof AiAnalysisRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthenticationRoute: typeof AuthenticationRoute
  CasesRoute: typeof CasesRoute
  EndpointRoute: typeof EndpointRoute
  FimRoute: typeof FimRoute
  HelpRoute: typeof HelpRoute
  IncidentsRoute: typeof IncidentsRoute
  IntegrationsRoute: typeof IntegrationsRoute
  IocRoute: typeof IocRoute
  LiveLogsRoute: typeof LiveLogsRoute
  MitreRoute: typeof MitreRoute
  NetworkRoute: typeof NetworkRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  RulesRoute: typeof RulesRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  ThreatIntelRoute: typeof ThreatIntelRoute
  UbaRoute: typeof UbaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uba': {
      id: '/uba'
      path: '/uba'
      fullPath: '/uba'
      preLoaderRoute: typeof UbaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threat-intel': {
      id: '/threat-intel'
      path: '/threat-intel'
      fullPath: '/threat-intel'
      preLoaderRoute: typeof ThreatIntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitre': {
      id: '/mitre'
      path: '/mitre'
      fullPath: '/mitre'
      preLoaderRoute: typeof MitreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-logs': {
      id: '/live-logs'
      path: '/live-logs'
      fullPath: '/live-logs'
      preLoaderRoute: typeof LiveLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ioc': {
      id: '/ioc'
      path: '/ioc'
      fullPath: '/ioc'
      preLoaderRoute: typeof IocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fim': {
      id: '/fim'
      path: '/fim'
      fullPath: '/fim'
      preLoaderRoute: typeof FimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/endpoint': {
      id: '/endpoint'
      path: '/endpoint'
      fullPath: '/endpoint'
      preLoaderRoute: typeof EndpointRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authentication': {
      id: '/authentication'
      path: '/authentication'
      fullPath: '/authentication'
      preLoaderRoute: typeof AuthenticationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-analysis': {
      id: '/ai-analysis'
      path: '/ai-analysis'
      fullPath: '/ai-analysis'
      preLoaderRoute: typeof AiAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAnalysisRoute: AiAnalysisRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthenticationRoute: AuthenticationRoute,
  CasesRoute: CasesRoute,
  EndpointRoute: EndpointRoute,
  FimRoute: FimRoute,
  HelpRoute: HelpRoute,
  IncidentsRoute: IncidentsRoute,
  IntegrationsRoute: IntegrationsRoute,
  IocRoute: IocRoute,
  LiveLogsRoute: LiveLogsRoute,
  MitreRoute: MitreRoute,
  NetworkRoute: NetworkRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  RulesRoute: RulesRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  ThreatIntelRoute: ThreatIntelRoute,
  UbaRoute: UbaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
